site_name: UnelmaPay API Documentation
site_url: https://docs.unelmapay.com
repo_url: https://github.com/unellma/UnelmaPay-developers
site_description: Comprehensive documentation for UnelmaPay API integration
site_author: UnelmaPay Team

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.indexes
    - navigation.instant
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - toc:
      permalink: true
  - pymdownx.tabbed
  - pymdownx.snippets
  - admonition
  - meta
  - attr_list
  - pymdownx.details
  - pymdownx.superfences

plugins:
  - search
  - minify:
      minify_html: true

nav:
  - Home: index.md
  - Getting Started:
    - Overview: getting-started/overview.md
  - API Reference:
    - Payment Form: api/payment-form.md
    - IPN Callback: api/ipn-callback.md
  - Testing:
    - Testing Guide: guides/testing.md
  - Support:
    - Contact: support.md
